--------------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
--------------------------------------------------------------------------------
--  Name......: remove.sql
--  Author....: Stefan Oehrli (oes) stefan.oehrli@oradba.com
--  Editor....: Stefan Oehrli
--  Date......: 2023.05.22
--  Revision..:  
--  Purpose...: SQL script to remove the SecBench PDB configuration
--  Notes.....:  
--  Reference.: SYS (or grant manually to a DBA)
--  License...: Apache License Version 2.0, January 2004 as shown
--              at http://www.apache.org/licenses/
--------------------------------------------------------------------------------
-- setup SQLPlus environment
SET SERVEROUTPUT ON
SET LINESIZE 160 PAGESIZE 200
COL policy_name FOR A40
COL entity_name FOR A30
COL comments FOR A80

-- enable legacy audit stuff
NOAUDIT ALTER ANY TABLE BY ACCESS;
NOAUDIT CREATE ANY TABLE BY ACCESS;
NOAUDIT DROP ANY TABLE BY ACCESS;
NOAUDIT CREATE ANY PROCEDURE BY ACCESS;
NOAUDIT DROP ANY PROCEDURE BY ACCESS;
NOAUDIT ALTER ANY PROCEDURE BY ACCESS;
NOAUDIT GRANT ANY PRIVILEGE BY ACCESS;
NOAUDIT GRANT ANY OBJECT PRIVILEGE BY ACCESS;
NOAUDIT GRANT ANY ROLE BY ACCESS;
NOAUDIT AUDIT SYSTEM BY ACCESS;
NOAUDIT CREATE EXTERNAL JOB BY ACCESS;
NOAUDIT CREATE ANY JOB BY ACCESS;
NOAUDIT CREATE ANY LIBRARY BY ACCESS;
NOAUDIT CREATE PUBLIC DATABASE LINK BY ACCESS;
NOAUDIT EXEMPT ACCESS POLICY BY ACCESS;
NOAUDIT ALTER USER BY ACCESS;
NOAUDIT CREATE USER BY ACCESS;
NOAUDIT ROLE BY ACCESS;
NOAUDIT CREATE SESSION BY ACCESS;
NOAUDIT DROP USER BY ACCESS;
NOAUDIT ALTER DATABASE BY ACCESS;
NOAUDIT ALTER SYSTEM BY ACCESS;
NOAUDIT ALTER PROFILE BY ACCESS;
NOAUDIT DROP PROFILE BY ACCESS;
NOAUDIT DATABASE LINK BY ACCESS;
NOAUDIT SYSTEM AUDIT BY ACCESS;
NOAUDIT PROFILE BY ACCESS;
NOAUDIT PUBLIC SYNONYM BY ACCESS;
NOAUDIT SYSTEM GRANT BY ACCESS;
NOAUDIT CREATE SQL TRANSLATION PROFILE BY ACCESS;
NOAUDIT CREATE ANY SQL TRANSLATION PROFILE BY ACCESS;
NOAUDIT DROP ANY SQL TRANSLATION PROFILE BY ACCESS;
NOAUDIT ALTER ANY SQL TRANSLATION PROFILE BY ACCESS;
NOAUDIT TRANSLATE ANY SQL BY ACCESS;
NOAUDIT PURGE DBA_RECYCLEBIN BY ACCESS;
NOAUDIT LOGMINING BY ACCESS;
NOAUDIT EXEMPT REDACTION POLICY BY ACCESS;
NOAUDIT ADMINISTER KEY MANAGEMENT BY ACCESS;
NOAUDIT DIRECTORY BY ACCESS;
NOAUDIT PLUGGABLE DATABASE BY ACCESS;
NOAUDIT BECOME USER BY ACCESS;

-- List enabled audit policies
SELECT * FROM audit_unified_enabled_policies;

-- list legacy audit
COL user_name FOR A10
COL proxy_name FOR A10
COL audit_option FOR A40
COL success FOR A10
COL failure FOR A10
SELECT * FROM dba_stmt_audit_opts;
-- EOF ---------------------------------------------------------------------
